twig:
    file_name_pattern: '*.twig'

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': styles

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_horizontal_layout.html.twig']
